# frozen_string_literal: true

###
# API endpoints for the RubyGem package registry
module API
  class RubygemPackages < ::API::Base
    include SendFileUpload

    # The Marshal version can be found by "#{Marshal::MAJOR_VERSION}.#{Marshal::MINOR_VERSION}"
    # Updating the version should require a GitLab API version change.
    MARSHAL_VERSION = '4.8'

    helpers ::API::Helpers::PackagesHelpers

    content_type :binary, 'application/octet-stream'

    before do
      not_found! unless Feature.enabled(:rubygem_packages, user_project)
      require_packages_enabled!
      authenticate!
    end

    params do
      requires :id, type: String, desc: 'The ID or full path of a project'
    end
    resource :projects do
      namespace ':id/packages/rubygems' do
        desc 'Download the spec index file' do
          detail 'This feature was introduced in GitLab 13.9'
        end
        params do
          requires :file_name, type: String, desc: 'Spec file name'
        end
        get ":file_name" do
          not_found!
        end

        desc 'Download the gemspec file' do
          detail 'This feature was introduced in GitLab 13.9'
        end
        params do
          requires :file_name, type: String, desc: 'Gemspec file name'
        end
        get "quick/Marshal.#{MARSHAL_VERSION}/:file_name" do
          not_found!
        end

        desc 'Download the .gem package' do
          detail 'This feature was introduced in GitLab 13.9'
        end
        params do
          requires :file_name, type: String, desc: 'Package file name'
        end
        get "gems/:file_name" do
          not_found!
        end

        namespace 'api/v1' do
          desc 'Authenticate with the registry' do
            detail 'This feature was introduced in GitLab 13.9'
          end
          route_setting :authentication, job_token_allowed: true, deploy_token_allowed: true
          get 'api_key' do
            authorize_read_package!

            { "rubygems_api_key": "701243f217cdf23b1370c7b66b65ca97" }
          end

          desc 'Authorize a gem upload' do
            detail 'This feature was introduced in GitLab 13.9'
          end
          post 'gems/authorize' do
            not_found!
          end

          desc 'Upload a gem' do
            detail 'This feature was introduced in GitLab 13.9'
          end
          params do
            requires :file, type: ::API::Validations::Types::WorkhorseFile, desc: 'The package file to be published (generated by Multipart middleware)'
          end
          post 'gems' do
            not_found!
          end

          desc 'Fetch a list of dependencies' do
            detail 'This feature was introduced in GitLab 13.9'
          end
          params do
            optional :gems, type: String, desc: 'Comma delimited gem names'
          end
          get 'dependencies' do
            not_found!
          end
        end
      end
    end
  end
end
