# frozen_string_literal: true

has_startup_css_changes = helper.all_changed_files.grep(%r{stylesheets/startup}).any?

if has_startup_css_changes
  new_mr_title = helper.mr_title.dup
  new_mr_title << ' [RUN AS-IF-FOSS]' unless helper.run_as_if_foss_mr?

  changes = {}

  if new_mr_title != helper.mr_title
    changes[:title] = new_mr_title
  else
    message "You're adding or removing a feature flag, your MR title needs to include `[RUN AS-IF-FOSS]` (we may have updated it automatically for you and started a new MR pipeline) to ensure everything is covered."
  end

  if changes.any?
    gitlab.api.update_merge_request(
      gitlab.mr_json['project_id'],
      gitlab.mr_json['iid'],
      **changes
    )
    gitlab.api.post("/projects/#{gitlab.mr_json['project_id']}/merge_requests/#{gitlab.mr_json['iid']}/pipelines")
  end
end
