# frozen_string_literal: true

PATTERNS = %w[
  createFlash
  gl-deprecated-button
  loading-button
  pagination-button
  gl-deprecated-dropdown
  gl-deprecated-dropdown-divider
  gl-deprecated-dropdown-header
  gl-deprecated-dropdown-item
  initDeprecatedJQueryDropdown
].freeze

BLOCKING_PATTERNS = %w[
].freeze

def get_added_lines(files)
  lines = []
  files.each do |file|
    lines += helper.changed_lines(file).select { |line| %r{^[+]}.match?(line) }
  end
  lines
end

changed_vue_haml_files = helper.changed_files(/.vue$|.haml$/)

return if changed_vue_haml_files.empty?

changed_lines_in_mr = get_added_lines(changed_vue_haml_files)
has_deprecated_components = changed_lines_in_mr.select { |i| i[/#{PATTERNS.join("|")}/] }
deprecated_components_in_mr = PATTERNS.select { |s| has_deprecated_components.join(" ")[s] }

has_blocking_components = changed_lines_in_mr.select { |i| i[/#{BLOCKING_PATTERNS.join("|")}/] }
blocking_components_in_mr = BLOCKING_PATTERNS.select { |s| has_blocking_components.join(" ")[s] }

return if (deprecated_components_in_mr + blocking_components_in_mr).empty?

if blocking_components_in_mr.any?
  fail "This merge request contains deprecated components that have been migrated and can no longer be used. Please use Pajamas components instead."
end

if deprecated_components_in_mr.any?
  warn "This merge request contains deprecated components. Please consider using Pajamas components instead."
end

markdown(<<~MARKDOWN)
  ## Deprecated components

  The following components are deprecated:

  * #{(blocking_components_in_mr + deprecated_components_in_mr).join("\n* ")}

  Please use [Pajamas components](https://design.gitlab.com/components/status/) instead.
MARKDOWN
