# frozen_string_literal: true

SortingTitlesValues = OpenStruct.new(
  # Titles
  sort_title_access_level_asc: s_('SortOptions|Access level, ascending'),
  sort_title_access_level_desc: s_('SortOptions|Access level, descending'),
  sort_title_created_date: s_('SortOptions|Created date'),
  sort_title_downvotes: s_('SortOptions|Least popular'),
  sort_title_due_date: s_('SortOptions|Due date'),
  sort_title_due_date_later: s_('SortOptions|Due later'),
  sort_title_due_date_soon: s_('SortOptions|Due soon'),
  sort_title_label_priority: s_('SortOptions|Label priority'),
  sort_title_largest_group: s_('SortOptions|Largest group'),
  sort_title_largest_repo: s_('SortOptions|Largest repository'),
  sort_title_last_joined: s_('SortOptions|Last joined'),
  sort_title_latest_activity: s_('SortOptions|Last updated'),
  sort_title_milestone: s_('SortOptions|Milestone due date'),
  sort_title_milestone_later: s_('SortOptions|Milestone due later'),
  sort_title_milestone_soon: s_('SortOptions|Milestone due soon'),
  sort_title_name: s_('SortOptions|Name'),
  sort_title_name_asc: s_('SortOptions|Name, ascending'),
  sort_title_name_desc: s_('SortOptions|Name, descending'),
  sort_title_oldest_activity: s_('SortOptions|Oldest updated'),
  sort_title_oldest_created: s_('SortOptions|Oldest created'),
  sort_title_oldest_joined: s_('SortOptions|Oldest joined'),
  sort_title_oldest_signin: s_('SortOptions|Oldest sign in'),
  sort_title_oldest_starred: s_('SortOptions|Oldest starred'),
  sort_title_oldest_updated: s_('SortOptions|Oldest updated'),
  sort_title_popularity: s_('SortOptions|Popularity'),
  sort_title_priority: s_('SortOptions|Priority'),
  sort_title_recently_created: s_('SortOptions|Last created'),
  sort_title_recently_signin: s_('SortOptions|Recent sign in'),
  sort_title_recently_starred: s_('SortOptions|Recently starred'),
  sort_title_recently_updated: s_('SortOptions|Last updated'),
  sort_title_start_date_later: s_('SortOptions|Start later'),
  sort_title_start_date_soon: s_('SortOptions|Start soon'),
  sort_title_upvotes: s_('SortOptions|Most popular'),
  sort_title_contacted_date: s_('SortOptions|Last Contact'),
  sort_title_most_stars: s_('SortOptions|Most stars'),
  sort_title_stars: s_('SortOptions|Stars'),
  sort_title_oldest_last_activity: s_('SortOptions|Oldest last activity'),
  sort_title_recently_last_activity: s_('SortOptions|Recent last activity'),
  sort_title_relative_position: s_('SortOptions|Manual'),
  sort_title_size: s_('SortOptions|Size'),
  sort_title_expire_date: s_('SortOptions|Expired date'),
  sort_title_relevant: s_('SortOptions|Relevant'),
  # Values.
  sort_value_access_level_asc: 'access_level_asc',
  sort_value_access_level_desc: 'access_level_desc',
  sort_value_created_date: 'created_date',
  sort_value_downvotes: 'downvotes_desc',
  sort_value_due_date: 'due_date',
  sort_value_due_date_later: 'due_date_desc',
  sort_value_due_date_soon: 'due_date_asc',
  sort_value_label_priority: 'label_priority',
  sort_value_largest_group: 'storage_size_desc',
  sort_value_largest_repo: 'storage_size_desc',
  sort_value_last_joined: 'last_joined',
  sort_value_latest_activity: 'latest_activity_desc',
  sort_value_milestone: 'milestone',
  sort_value_milestone_later: 'milestone_due_desc',
  sort_value_milestone_soon: 'milestone_due_asc',
  sort_value_name: 'name_asc',
  sort_value_name_desc: 'name_desc',
  sort_value_oldest_activity: 'latest_activity_asc',
  sort_value_oldest_created: 'created_asc',
  sort_value_oldest_signin: 'oldest_sign_in',
  sort_value_oldest_joined: 'oldest_joined',
  sort_value_oldest_updated: 'updated_asc',
  sort_value_popularity: 'popularity',
  sort_value_most_popular: 'popularity_desc',
  sort_value_least_popular: 'popularity_asc',
  sort_value_priority: 'priority',
  sort_value_recently_created: 'created_desc',
  sort_value_recently_signin: 'recent_sign_in',
  sort_value_recently_updated: 'updated_desc',
  sort_value_start_date_later: 'start_date_desc',
  sort_value_start_date_soon: 'start_date_asc',
  sort_value_upvotes: 'upvotes_desc',
  sort_value_contacted_date: 'contacted_asc',
  sort_value_stars_desc: 'stars_desc',
  sort_value_stars_asc: 'stars_asc',
  sort_value_oldest_last_activity: 'last_activity_on_asc',
  sort_value_recently_last_activity: 'last_activity_on_desc',
  sort_value_relative_position: 'relative_position',
  sort_value_size: 'size_desc',
  sort_value_expire_date: 'expired_asc',
  sort_value_relevant: 'relevant'
)
