# frozen_string_literal: true
# rubocop:disable Style/SignalException

DATA_WAREHOUSE_LABELS = [
  "Data Warehouse::Impact Check",
  "Data Warehouse::Impacted",
  "Data Warehouse::Not Impacted"
].freeze

CHANGED_SCHEMA_MESSAGE = <<~MSG
To notify the Data Team about changes to the db/structure.sql file, add label `Data Warehouse::Impact Check`

/label ~"Data Warehouse::Impact Check"

MSG

db_schema_updated = !git.modified_files.grep(%r{\Adb/structure\.sql}).empty?

if db_schema_updated

  markdown(CHANGED_SCHEMA_MESSAGE)

end
