# frozen_string_literal: true

class DropCiForeignKeys < ActiveRecord::Migration[6.1]
  include Gitlab::Database::MigrationHelpers

  DOWNTIME = false

  disable_ddl_transaction!

  def up
    remove_foreign_key_if_exists(:ci_build_report_results, :projects, name: "fk_rails_056d298d48")
    remove_foreign_key_if_exists(:ci_build_trace_section_names, :projects, name: "fk_rails_f8cd72cd26")
    remove_foreign_key_if_exists(:ci_build_trace_sections, :projects, name: "fk_rails_ab7c104e26")
    remove_foreign_key_if_exists(:ci_builds, :projects, name: "fk_befce0568a")
    remove_foreign_key_if_exists(:ci_builds_metadata, :projects, name: "fk_rails_ffcf702a02")
    remove_foreign_key_if_exists(:ci_daily_build_group_report_results, :namespaces, name: "fk_fd1858fefd")
    remove_foreign_key_if_exists(:ci_daily_build_group_report_results, :projects, name: "fk_rails_0667f7608c")
    remove_foreign_key_if_exists(:ci_freeze_periods, :projects, name: "fk_2e02bbd1a6")
    remove_foreign_key_if_exists(:ci_group_variables, :namespaces, name: "fk_33ae4d58d8")
    remove_foreign_key_if_exists(:ci_job_artifacts, :projects, name: "fk_rails_9862d392f9")
    remove_foreign_key_if_exists(:ci_job_token_project_scope_links, :users, name: "fk_rails_35f7f506ce")
    remove_foreign_key_if_exists(:ci_job_token_project_scope_links, :projects, name: "fk_rails_4b2ee3290b")
    remove_foreign_key_if_exists(:ci_job_token_project_scope_links, :projects, name: "fk_rails_6904b38465")
    remove_foreign_key_if_exists(:ci_minutes_additional_packs, :namespaces, name: "fk_rails_e0e0c4e4b1")
    remove_foreign_key_if_exists(:ci_pending_builds, :projects, name: "fk_rails_480669c3b3")
    remove_foreign_key_if_exists(:ci_pipeline_artifacts, :projects, name: "fk_rails_4a70390ca6")
    remove_foreign_key_if_exists(:ci_pipeline_chat_data, :chat_names, name: "fk_rails_f300456b63")
    remove_foreign_key_if_exists(:ci_pipeline_schedules, :projects, name: "fk_8ead60fcc4")
    remove_foreign_key_if_exists(:ci_pipeline_schedules, :users, name: "fk_9ea99f58d2")
    remove_foreign_key_if_exists(:ci_pipelines, :external_pull_requests, name: "fk_190998ef09")
    remove_foreign_key_if_exists(:ci_pipelines, :projects, name: "fk_86635dbd80")
    remove_foreign_key_if_exists(:ci_pipelines, :merge_requests, name: "fk_a23be95014")
    remove_foreign_key_if_exists(:ci_project_monthly_usages, :projects, name: "fk_rails_508bcd4aa6")
    remove_foreign_key_if_exists(:ci_refs, :projects, name: "fk_rails_4249db8cc3")
    remove_foreign_key_if_exists(:ci_resource_groups, :projects, name: "fk_774722d144")
    remove_foreign_key_if_exists(:ci_runner_namespaces, :namespaces, name: "fk_rails_f9d9ed3308")
    remove_foreign_key_if_exists(:ci_runner_projects, :projects, name: "fk_4478a6f1e4")
    remove_foreign_key_if_exists(:ci_running_builds, :projects, name: "fk_rails_dc1d0801e8")
    remove_foreign_key_if_exists(:ci_sources_pipelines, :projects, name: "fk_1e53c97c0a")
    remove_foreign_key_if_exists(:ci_sources_pipelines, :projects, name: "fk_acd9737679")
    remove_foreign_key_if_exists(:ci_sources_projects, :projects, name: "fk_rails_64b6855cbc")
    remove_foreign_key_if_exists(:ci_stages, :projects, name: "fk_2360681d1d")
    remove_foreign_key_if_exists(:ci_subscriptions_projects, :projects, name: "fk_rails_0818751483")
    remove_foreign_key_if_exists(:ci_subscriptions_projects, :projects, name: "fk_rails_7871f9a97b")
    remove_foreign_key_if_exists(:ci_triggers, :projects, name: "fk_e3e63f966e")
    remove_foreign_key_if_exists(:ci_triggers, :users, name: "fk_e8e10d1964")
    remove_foreign_key_if_exists(:ci_unit_tests, :projects, name: "fk_7a8fabf0a8")
    remove_foreign_key_if_exists(:ci_variables, :projects, name: "fk_ada5eb64b3")
    remove_foreign_key_if_exists(:ci_test_case_failures, :ci_builds, name: "fk_d69404d827")
    remove_foreign_key_if_exists(:clusters_applications_runners, :ci_runners, name: "fk_02de2ded36")
    remove_foreign_key_if_exists(:dast_profiles_pipelines, :ci_pipelines, name: "fk_a60cad829d")
    remove_foreign_key_if_exists(:dast_scanner_profiles_builds, :ci_builds, name: "fk_e4c49200f8")
    remove_foreign_key_if_exists(:dast_site_profiles_builds, :ci_builds, name: "fk_a325505e99")
    remove_foreign_key_if_exists(:dast_site_profiles_pipelines, :ci_pipelines, name: "fk_53849b0ad5")
    remove_foreign_key_if_exists(:merge_request_metrics, :ci_pipelines, name: "fk_rails_33ae169d48")
    remove_foreign_key_if_exists(:merge_requests, :ci_pipelines, name: "fk_fd82eae0b9")
    remove_foreign_key_if_exists(:merge_trains, :ci_pipelines, name: "fk_rails_f90820cb08")
    remove_foreign_key_if_exists(:packages_build_infos, :ci_pipelines, name: "fk_rails_17a9a0dffc")
    remove_foreign_key_if_exists(:packages_package_file_build_infos, :ci_pipelines, name: "fk_rails_3e3f630188")
    remove_foreign_key_if_exists(:pages_deployments, :ci_builds, name: "fk_rails_c3a90cf29b")
    remove_foreign_key_if_exists(:project_pages_metadata, :ci_job_artifacts, name: "fk_69366a119e")
    remove_foreign_key_if_exists(:requirements_management_test_reports, :ci_builds, name: "fk_rails_e67d085910")
    remove_foreign_key_if_exists(:security_scans, :ci_builds, name: "fk_rails_4ef1e6b4c6")
    remove_foreign_key_if_exists(:terraform_state_versions, :ci_builds, name: "fk_04b91e4a9f")
    remove_foreign_key_if_exists(:vulnerability_feedback, :ci_pipelines, name: "fk_rails_20976e6fd9")
    remove_foreign_key_if_exists(:vulnerability_occurrence_pipelines, :ci_pipelines, name: "fk_rails_6421e35d7d")
    remove_foreign_key_if_exists(:vulnerability_statistics, :ci_pipelines, name: "fk_e8b13c928f")
  end

  def down
    add_concurrent_foreign_key(:ci_build_report_results, :projects, name: "fk_rails_056d298d48", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_build_trace_section_names, :projects, name: "fk_rails_f8cd72cd26", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_build_trace_sections, :projects, name: "fk_rails_ab7c104e26", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_builds, :projects, name: "fk_befce0568a", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_builds_metadata, :projects, name: "fk_rails_ffcf702a02", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_daily_build_group_report_results, :namespaces, name: "fk_fd1858fefd", column: :group_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_daily_build_group_report_results, :projects, name: "fk_rails_0667f7608c", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_freeze_periods, :projects, name: "fk_2e02bbd1a6", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_group_variables, :namespaces, name: "fk_33ae4d58d8", column: :group_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_job_artifacts, :projects, name: "fk_rails_9862d392f9", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_job_token_project_scope_links, :users, name: "fk_rails_35f7f506ce", column: :added_by_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:ci_job_token_project_scope_links, :projects, name: "fk_rails_4b2ee3290b", column: :source_project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_job_token_project_scope_links, :projects, name: "fk_rails_6904b38465", column: :target_project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_minutes_additional_packs, :namespaces, name: "fk_rails_e0e0c4e4b1", column: :namespace_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_pending_builds, :projects, name: "fk_rails_480669c3b3", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_pipeline_artifacts, :projects, name: "fk_rails_4a70390ca6", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_pipeline_chat_data, :chat_names, name: "fk_rails_f300456b63", column: :chat_name_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_pipeline_schedules, :projects, name: "fk_8ead60fcc4", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_pipeline_schedules, :users, name: "fk_9ea99f58d2", column: :owner_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:ci_pipelines, :external_pull_requests, name: "fk_190998ef09", column: :external_pull_request_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:ci_pipelines, :projects, name: "fk_86635dbd80", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_pipelines, :merge_requests, name: "fk_a23be95014", column: :merge_request_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_project_monthly_usages, :projects, name: "fk_rails_508bcd4aa6", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_refs, :projects, name: "fk_rails_4249db8cc3", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_resource_groups, :projects, name: "fk_774722d144", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_runner_namespaces, :namespaces, name: "fk_rails_f9d9ed3308", column: :namespace_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_runner_projects, :projects, name: "fk_4478a6f1e4", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_running_builds, :projects, name: "fk_rails_dc1d0801e8", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_sources_pipelines, :projects, name: "fk_1e53c97c0a", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_sources_pipelines, :projects, name: "fk_acd9737679", column: :source_project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_sources_projects, :projects, name: "fk_rails_64b6855cbc", column: :source_project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_stages, :projects, name: "fk_2360681d1d", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_subscriptions_projects, :projects, name: "fk_rails_0818751483", column: :downstream_project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_subscriptions_projects, :projects, name: "fk_rails_7871f9a97b", column: :upstream_project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_triggers, :projects, name: "fk_e3e63f966e", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_triggers, :users, name: "fk_e8e10d1964", column: :owner_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_unit_tests, :projects, name: "fk_7a8fabf0a8", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_variables, :projects, name: "fk_ada5eb64b3", column: :project_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:ci_test_case_failures, :ci_builds, name: "fk_d69404d827", column: :build_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:clusters_applications_runners, :ci_runners, name: "fk_02de2ded36", column: :runner_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:dast_profiles_pipelines, :ci_pipelines, name: "fk_a60cad829d", column: :ci_pipeline_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:dast_scanner_profiles_builds, :ci_builds, name: "fk_e4c49200f8", column: :ci_build_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:dast_site_profiles_builds, :ci_builds, name: "fk_a325505e99", column: :ci_build_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:dast_site_profiles_pipelines, :ci_pipelines, name: "fk_53849b0ad5", column: :ci_pipeline_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:merge_request_metrics, :ci_pipelines, name: "fk_rails_33ae169d48", column: :pipeline_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:merge_requests, :ci_pipelines, name: "fk_fd82eae0b9", column: :head_pipeline_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:merge_trains, :ci_pipelines, name: "fk_rails_f90820cb08", column: :pipeline_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:packages_build_infos, :ci_pipelines, name: "fk_rails_17a9a0dffc", column: :pipeline_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:packages_package_file_build_infos, :ci_pipelines, name: "fk_rails_3e3f630188", column: :pipeline_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:pages_deployments, :ci_builds, name: "fk_rails_c3a90cf29b", column: :ci_build_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:project_pages_metadata, :ci_job_artifacts, name: "fk_69366a119e", column: :artifacts_archive_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:requirements_management_test_reports, :ci_builds, name: "fk_rails_e67d085910", column: :build_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:security_scans, :ci_builds, name: "fk_rails_4ef1e6b4c6", column: :build_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:terraform_state_versions, :ci_builds, name: "fk_04b91e4a9f", column: :ci_build_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:vulnerability_feedback, :ci_pipelines, name: "fk_rails_20976e6fd9", column: :pipeline_id, target_column: :id, on_delete: "nullify")
    add_concurrent_foreign_key(:vulnerability_occurrence_pipelines, :ci_pipelines, name: "fk_rails_6421e35d7d", column: :pipeline_id, target_column: :id, on_delete: "cascade")
    add_concurrent_foreign_key(:vulnerability_statistics, :ci_pipelines, name: "fk_e8b13c928f", column: :latest_pipeline_id, target_column: :id, on_delete: "nullify")
  end
end
