# frozen_string_literal: true

class MigrateAllToBigint < ActiveRecord::Migration[6.0]
  include Gitlab::Database::MigrationHelpers

  disable_ddl_transaction!

  def up
    execute <<-EOS
      DROP TRIGGER IF EXISTS trigger_has_external_issue_tracker_on_delete ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_issue_tracker_on_insert ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_issue_tracker_on_update ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_wiki_on_delete ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_wiki_on_insert ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_wiki_on_update ON services;
    EOS

    change_column :abuse_reports, :id, :bigint
    change_column :abuse_reports, :reporter_id, :bigint
    change_column :abuse_reports, :user_id, :bigint
    change_column :alert_management_alerts, :prometheus_alert_id, :bigint
    change_column :alert_management_alerts, :environment_id, :bigint
    change_column :allowed_email_domains, :group_id, :bigint
    change_column :analytics_devops_adoption_segments, :namespace_id, :bigint
    change_column :appearances, :id, :bigint
    change_column :application_setting_terms, :id, :bigint
    change_column :application_settings, :id, :bigint
    change_column :application_settings, :performance_bar_allowed_group_id, :bigint
    change_column :application_settings, :file_template_project_id, :bigint
    change_column :application_settings, :custom_project_templates_group_id, :bigint
    change_column :application_settings, :usage_stats_set_by_user_id, :bigint
    change_column :application_settings, :instance_administrators_group_id, :bigint
    change_column :approval_merge_request_rules, :merge_request_id, :bigint
    change_column :approval_merge_request_rules_approved_approvers, :user_id, :bigint
    change_column :approval_merge_request_rules_groups, :group_id, :bigint
    change_column :approval_merge_request_rules_users, :user_id, :bigint
    change_column :approval_project_rules, :project_id, :bigint
    change_column :approval_project_rules_groups, :group_id, :bigint
    change_column :approval_project_rules_users, :user_id, :bigint
    change_column :approvals, :id, :bigint
    change_column :approvals, :merge_request_id, :bigint
    change_column :approvals, :user_id, :bigint
    change_column :approver_groups, :id, :bigint
    change_column :approver_groups, :target_id, :bigint
    change_column :approver_groups, :group_id, :bigint
    change_column :approvers, :id, :bigint
    change_column :approvers, :target_id, :bigint
    change_column :approvers, :user_id, :bigint
    change_column :audit_events, :author_id, :bigint
    change_column :audit_events, :entity_id, :bigint
    change_column :award_emoji, :id, :bigint
    change_column :award_emoji, :user_id, :bigint
    change_column :award_emoji, :awardable_id, :bigint
    change_column :aws_roles, :user_id, :bigint
    change_column :badges, :id, :bigint
    change_column :badges, :project_id, :bigint
    change_column :badges, :group_id, :bigint
    change_column :board_assignees, :id, :bigint
    change_column :board_assignees, :board_id, :bigint
    change_column :board_assignees, :assignee_id, :bigint
    change_column :board_group_recent_visits, :user_id, :bigint
    change_column :board_group_recent_visits, :board_id, :bigint
    change_column :board_group_recent_visits, :group_id, :bigint
    change_column :board_labels, :id, :bigint
    change_column :board_labels, :board_id, :bigint
    change_column :board_labels, :label_id, :bigint
    change_column :board_project_recent_visits, :user_id, :bigint
    change_column :board_project_recent_visits, :project_id, :bigint
    change_column :board_project_recent_visits, :board_id, :bigint
    change_column :boards, :id, :bigint
    change_column :boards, :project_id, :bigint
    change_column :boards, :milestone_id, :bigint
    change_column :boards, :group_id, :bigint
    change_column :broadcast_messages, :id, :bigint
    change_column :bulk_import_configurations, :bulk_import_id, :bigint
    change_column :bulk_imports, :user_id, :bigint
    change_column :chat_names, :id, :bigint
    change_column :chat_names, :user_id, :bigint
    change_column :chat_names, :service_id, :bigint
    change_column :chat_teams, :id, :bigint
    change_column :chat_teams, :namespace_id, :bigint
    change_column :ci_build_needs, :id, :bigint
    change_column :ci_build_needs, :build_id, :bigint
    change_column :ci_build_trace_chunks, :build_id, :bigint
    change_column :ci_build_trace_section_names, :id, :bigint
    change_column :ci_build_trace_section_names, :project_id, :bigint
    change_column :ci_build_trace_sections, :project_id, :bigint
    change_column :ci_build_trace_sections, :build_id, :bigint
    change_column :ci_build_trace_sections, :section_name_id, :bigint
    change_column :ci_builds, :id, :bigint
    change_column :ci_builds, :runner_id, :bigint
    change_column :ci_builds, :commit_id, :bigint
    change_column :ci_builds, :trigger_request_id, :bigint
    change_column :ci_builds, :user_id, :bigint
    change_column :ci_builds, :project_id, :bigint
    change_column :ci_builds, :erased_by_id, :bigint
    change_column :ci_builds, :auto_canceled_by_id, :bigint
    change_column :ci_builds, :stage_id, :bigint
    change_column :ci_builds, :upstream_pipeline_id, :bigint
    change_column :ci_builds_metadata, :id, :bigint
    change_column :ci_builds_metadata, :build_id, :bigint
    change_column :ci_builds_metadata, :project_id, :bigint
    change_column :ci_builds_runner_session, :build_id, :bigint
    change_column :ci_group_variables, :id, :bigint
    change_column :ci_group_variables, :group_id, :bigint
    change_column :ci_job_artifacts, :id, :bigint
    change_column :ci_job_artifacts, :project_id, :bigint
    change_column :ci_job_artifacts, :job_id, :bigint
    change_column :ci_pipeline_chat_data, :pipeline_id, :bigint
    change_column :ci_pipeline_chat_data, :chat_name_id, :bigint
    change_column :ci_pipeline_messages, :pipeline_id, :bigint
    change_column :ci_pipeline_schedule_variables, :id, :bigint
    change_column :ci_pipeline_schedule_variables, :pipeline_schedule_id, :bigint
    change_column :ci_pipeline_schedules, :id, :bigint
    change_column :ci_pipeline_schedules, :project_id, :bigint
    change_column :ci_pipeline_schedules, :owner_id, :bigint
    change_column :ci_pipeline_variables, :id, :bigint
    change_column :ci_pipeline_variables, :pipeline_id, :bigint
    change_column :ci_pipelines, :id, :bigint
    change_column :ci_pipelines, :project_id, :bigint
    change_column :ci_pipelines, :user_id, :bigint
    change_column :ci_pipelines, :auto_canceled_by_id, :bigint
    change_column :ci_pipelines, :pipeline_schedule_id, :bigint
    change_column :ci_pipelines, :merge_request_id, :bigint
    change_column :ci_runner_namespaces, :id, :bigint
    change_column :ci_runner_namespaces, :runner_id, :bigint
    change_column :ci_runner_namespaces, :namespace_id, :bigint
    change_column :ci_runner_projects, :id, :bigint
    change_column :ci_runner_projects, :runner_id, :bigint
    change_column :ci_runner_projects, :project_id, :bigint
    change_column :ci_runners, :id, :bigint
    change_column :ci_sources_pipelines, :id, :bigint
    change_column :ci_sources_pipelines, :project_id, :bigint
    change_column :ci_sources_pipelines, :pipeline_id, :bigint
    change_column :ci_sources_pipelines, :source_project_id, :bigint
    change_column :ci_sources_pipelines, :source_job_id, :bigint
    change_column :ci_sources_pipelines, :source_pipeline_id, :bigint
    change_column :ci_stages, :id, :bigint
    change_column :ci_stages, :project_id, :bigint
    change_column :ci_stages, :pipeline_id, :bigint
    change_column :ci_trigger_requests, :id, :bigint
    change_column :ci_trigger_requests, :trigger_id, :bigint
    change_column :ci_trigger_requests, :commit_id, :bigint
    change_column :ci_triggers, :id, :bigint
    change_column :ci_triggers, :project_id, :bigint
    change_column :ci_triggers, :owner_id, :bigint
    change_column :ci_variables, :id, :bigint
    change_column :ci_variables, :project_id, :bigint
    change_column :cluster_groups, :id, :bigint
    change_column :cluster_groups, :cluster_id, :bigint
    change_column :cluster_groups, :group_id, :bigint
    change_column :cluster_platforms_kubernetes, :id, :bigint
    change_column :cluster_platforms_kubernetes, :cluster_id, :bigint
    change_column :cluster_projects, :id, :bigint
    change_column :cluster_projects, :project_id, :bigint
    change_column :cluster_projects, :cluster_id, :bigint
    change_column :cluster_providers_gcp, :id, :bigint
    change_column :cluster_providers_gcp, :cluster_id, :bigint
    change_column :clusters, :id, :bigint
    change_column :clusters, :user_id, :bigint
    change_column :clusters, :management_project_id, :bigint
    change_column :clusters_applications_cert_managers, :id, :bigint
    change_column :clusters_applications_cert_managers, :cluster_id, :bigint
    change_column :clusters_applications_crossplane, :id, :bigint
    change_column :clusters_applications_helm, :id, :bigint
    change_column :clusters_applications_helm, :cluster_id, :bigint
    change_column :clusters_applications_ingress, :id, :bigint
    change_column :clusters_applications_ingress, :cluster_id, :bigint
    change_column :clusters_applications_jupyter, :id, :bigint
    change_column :clusters_applications_jupyter, :cluster_id, :bigint
    change_column :clusters_applications_jupyter, :oauth_application_id, :bigint
    change_column :clusters_applications_knative, :id, :bigint
    change_column :clusters_applications_knative, :cluster_id, :bigint
    change_column :clusters_applications_prometheus, :id, :bigint
    change_column :clusters_applications_prometheus, :cluster_id, :bigint
    change_column :clusters_applications_runners, :id, :bigint
    change_column :clusters_applications_runners, :cluster_id, :bigint
    change_column :clusters_applications_runners, :runner_id, :bigint
    change_column :clusters_kubernetes_namespaces, :cluster_id, :bigint
    change_column :clusters_kubernetes_namespaces, :project_id, :bigint
    change_column :clusters_kubernetes_namespaces, :cluster_project_id, :bigint
    change_column :commit_user_mentions, :note_id, :bigint
    change_column :compliance_management_frameworks, :namespace_id, :bigint
    change_column :container_repositories, :id, :bigint
    change_column :container_repositories, :project_id, :bigint
    change_column :conversational_development_index_metrics, :id, :bigint
    change_column :dast_scanner_profiles, :project_id, :bigint
    change_column :dependency_proxy_blobs, :id, :bigint
    change_column :dependency_proxy_blobs, :group_id, :bigint
    change_column :dependency_proxy_group_settings, :id, :bigint
    change_column :dependency_proxy_group_settings, :group_id, :bigint
    change_column :deploy_keys_projects, :id, :bigint
    change_column :deploy_keys_projects, :deploy_key_id, :bigint
    change_column :deploy_keys_projects, :project_id, :bigint
    change_column :deploy_tokens, :id, :bigint
    change_column :deployment_clusters, :deployment_id, :bigint
    change_column :deployment_clusters, :cluster_id, :bigint
    change_column :deployment_merge_requests, :deployment_id, :bigint
    change_column :deployment_merge_requests, :merge_request_id, :bigint
    change_column :deployment_merge_requests, :environment_id, :bigint
    change_column :deployments, :id, :bigint
    change_column :deployments, :project_id, :bigint
    change_column :deployments, :environment_id, :bigint
    change_column :deployments, :user_id, :bigint
    change_column :deployments, :deployable_id, :bigint
    change_column :deployments, :cluster_id, :bigint
    change_column :description_versions, :issue_id, :bigint
    change_column :description_versions, :merge_request_id, :bigint
    change_column :description_versions, :epic_id, :bigint
    change_column :design_management_designs, :project_id, :bigint
    change_column :design_management_designs, :issue_id, :bigint
    change_column :design_management_versions, :author_id, :bigint
    change_column :design_user_mentions, :design_id, :bigint
    change_column :design_user_mentions, :note_id, :bigint
    change_column :draft_notes, :merge_request_id, :bigint
    change_column :draft_notes, :author_id, :bigint
    change_column :elasticsearch_indexed_namespaces, :namespace_id, :bigint
    change_column :elasticsearch_indexed_projects, :project_id, :bigint
    change_column :emails, :id, :bigint
    change_column :emails, :user_id, :bigint
    change_column :environments, :id, :bigint
    change_column :environments, :project_id, :bigint
    change_column :epic_issues, :id, :bigint
    change_column :epic_issues, :epic_id, :bigint
    change_column :epic_issues, :issue_id, :bigint
    change_column :epic_metrics, :id, :bigint
    change_column :epic_metrics, :epic_id, :bigint
    change_column :epic_user_mentions, :epic_id, :bigint
    change_column :epic_user_mentions, :note_id, :bigint
    change_column :epics, :id, :bigint
    change_column :epics, :group_id, :bigint
    change_column :epics, :author_id, :bigint
    change_column :epics, :assignee_id, :bigint
    change_column :epics, :updated_by_id, :bigint
    change_column :epics, :last_edited_by_id, :bigint
    change_column :epics, :start_date_sourcing_milestone_id, :bigint
    change_column :epics, :due_date_sourcing_milestone_id, :bigint
    change_column :epics, :closed_by_id, :bigint
    change_column :epics, :parent_id, :bigint
    change_column :epics, :start_date_sourcing_epic_id, :bigint
    change_column :epics, :due_date_sourcing_epic_id, :bigint
    change_column :events, :id, :bigint
    change_column :events, :project_id, :bigint
    change_column :events, :author_id, :bigint
    change_column :events, :target_id, :bigint
    change_column :feature_gates, :id, :bigint
    change_column :features, :id, :bigint
    change_column :fork_network_members, :id, :bigint
    change_column :fork_network_members, :fork_network_id, :bigint
    change_column :fork_network_members, :project_id, :bigint
    change_column :fork_network_members, :forked_from_project_id, :bigint
    change_column :fork_networks, :id, :bigint
    change_column :fork_networks, :root_project_id, :bigint
    change_column :geo_container_repository_updated_events, :container_repository_id, :bigint
    change_column :geo_event_log, :geo_event_id, :bigint
    change_column :geo_hashed_storage_attachments_events, :project_id, :bigint
    change_column :geo_hashed_storage_migrated_events, :project_id, :bigint
    change_column :geo_job_artifact_deleted_events, :job_artifact_id, :bigint
    change_column :geo_lfs_object_deleted_events, :lfs_object_id, :bigint
    change_column :geo_node_namespace_links, :id, :bigint
    change_column :geo_node_namespace_links, :geo_node_id, :bigint
    change_column :geo_node_namespace_links, :namespace_id, :bigint
    change_column :geo_node_statuses, :id, :bigint
    change_column :geo_node_statuses, :geo_node_id, :bigint
    change_column :geo_node_statuses, :last_event_id, :bigint
    change_column :geo_node_statuses, :cursor_last_event_id, :bigint
    change_column :geo_nodes, :id, :bigint
    change_column :geo_nodes, :oauth_application_id, :bigint
    change_column :geo_repositories_changed_events, :geo_node_id, :bigint
    change_column :geo_repository_created_events, :project_id, :bigint
    change_column :geo_repository_deleted_events, :project_id, :bigint
    change_column :geo_repository_renamed_events, :project_id, :bigint
    change_column :geo_repository_updated_events, :project_id, :bigint
    change_column :geo_reset_checksum_events, :project_id, :bigint
    change_column :geo_upload_deleted_events, :upload_id, :bigint
    change_column :geo_upload_deleted_events, :model_id, :bigint
    change_column :gitlab_subscription_histories, :namespace_id, :bigint
    change_column :gitlab_subscription_histories, :hosted_plan_id, :bigint
    change_column :gitlab_subscriptions, :namespace_id, :bigint
    change_column :gitlab_subscriptions, :hosted_plan_id, :bigint
    change_column :gpg_key_subkeys, :id, :bigint
    change_column :gpg_key_subkeys, :gpg_key_id, :bigint
    change_column :gpg_keys, :id, :bigint
    change_column :gpg_keys, :user_id, :bigint
    change_column :gpg_signatures, :id, :bigint
    change_column :gpg_signatures, :project_id, :bigint
    change_column :gpg_signatures, :gpg_key_id, :bigint
    change_column :gpg_signatures, :gpg_key_subkey_id, :bigint
    change_column :group_custom_attributes, :id, :bigint
    change_column :group_custom_attributes, :group_id, :bigint
    change_column :historical_data, :id, :bigint
    change_column :identities, :id, :bigint
    change_column :identities, :user_id, :bigint
    change_column :identities, :saml_provider_id, :bigint
    change_column :import_export_uploads, :id, :bigint
    change_column :import_export_uploads, :project_id, :bigint
    change_column :import_failures, :group_id, :bigint
    change_column :index_statuses, :id, :bigint
    change_column :index_statuses, :project_id, :bigint
    change_column :insights, :id, :bigint
    change_column :insights, :namespace_id, :bigint
    change_column :insights, :project_id, :bigint
    change_column :internal_ids, :project_id, :bigint
    change_column :internal_ids, :namespace_id, :bigint
    change_column :ip_restrictions, :group_id, :bigint
    change_column :issue_assignees, :user_id, :bigint
    change_column :issue_assignees, :issue_id, :bigint
    change_column :issue_links, :id, :bigint
    change_column :issue_links, :source_id, :bigint
    change_column :issue_links, :target_id, :bigint
    change_column :issue_metrics, :id, :bigint
    change_column :issue_metrics, :issue_id, :bigint
    change_column :issue_tracker_data, :service_id, :bigint
    change_column :issue_user_mentions, :issue_id, :bigint
    change_column :issue_user_mentions, :note_id, :bigint
    change_column :issues, :id, :bigint
    change_column :issues, :author_id, :bigint
    change_column :issues, :project_id, :bigint
    change_column :issues, :milestone_id, :bigint
    change_column :issues, :updated_by_id, :bigint
    change_column :issues, :moved_to_id, :bigint
    change_column :issues, :last_edited_by_id, :bigint
    change_column :issues, :closed_by_id, :bigint
    change_column :issues, :duplicated_to_id, :bigint
    change_column :issues, :promoted_to_epic_id, :bigint
    change_column :jira_connect_subscriptions, :namespace_id, :bigint
    change_column :jira_tracker_data, :service_id, :bigint
    change_column :keys, :id, :bigint
    change_column :keys, :user_id, :bigint
    change_column :label_links, :id, :bigint
    change_column :label_links, :label_id, :bigint
    change_column :label_links, :target_id, :bigint
    change_column :label_priorities, :id, :bigint
    change_column :label_priorities, :project_id, :bigint
    change_column :label_priorities, :label_id, :bigint
    change_column :labels, :id, :bigint
    change_column :labels, :project_id, :bigint
    change_column :labels, :group_id, :bigint
    change_column :ldap_group_links, :id, :bigint
    change_column :ldap_group_links, :group_id, :bigint
    change_column :lfs_file_locks, :id, :bigint
    change_column :lfs_file_locks, :project_id, :bigint
    change_column :lfs_file_locks, :user_id, :bigint
    change_column :lfs_objects, :id, :bigint
    change_column :lfs_objects_projects, :id, :bigint
    change_column :lfs_objects_projects, :lfs_object_id, :bigint
    change_column :lfs_objects_projects, :project_id, :bigint
    change_column :licenses, :id, :bigint
    change_column :lists, :id, :bigint
    change_column :lists, :board_id, :bigint
    change_column :lists, :label_id, :bigint
    change_column :lists, :user_id, :bigint
    change_column :lists, :milestone_id, :bigint
    change_column :members, :id, :bigint
    change_column :members, :source_id, :bigint
    change_column :members, :user_id, :bigint
    change_column :members, :created_by_id, :bigint
    change_column :merge_request_assignees, :user_id, :bigint
    change_column :merge_request_assignees, :merge_request_id, :bigint
    change_column :merge_request_blocks, :blocking_merge_request_id, :bigint
    change_column :merge_request_blocks, :blocked_merge_request_id, :bigint
    change_column :merge_request_diff_commits, :merge_request_diff_id, :bigint
    change_column :merge_request_diff_files, :merge_request_diff_id, :bigint
    change_column :merge_request_diffs, :id, :bigint
    change_column :merge_request_diffs, :merge_request_id, :bigint
    change_column :merge_request_metrics, :id, :bigint
    change_column :merge_request_metrics, :merge_request_id, :bigint
    change_column :merge_request_metrics, :pipeline_id, :bigint
    change_column :merge_request_metrics, :merged_by_id, :bigint
    change_column :merge_request_metrics, :latest_closed_by_id, :bigint
    change_column :merge_request_metrics, :target_project_id, :bigint
    change_column :merge_request_user_mentions, :merge_request_id, :bigint
    change_column :merge_request_user_mentions, :note_id, :bigint
    change_column :merge_requests, :id, :bigint
    change_column :merge_requests, :source_project_id, :bigint
    change_column :merge_requests, :author_id, :bigint
    change_column :merge_requests, :assignee_id, :bigint
    change_column :merge_requests, :milestone_id, :bigint
    change_column :merge_requests, :target_project_id, :bigint
    change_column :merge_requests, :updated_by_id, :bigint
    change_column :merge_requests, :merge_user_id, :bigint
    change_column :merge_requests, :last_edited_by_id, :bigint
    change_column :merge_requests, :head_pipeline_id, :bigint
    change_column :merge_requests, :latest_merge_request_diff_id, :bigint
    change_column :merge_requests_closing_issues, :id, :bigint
    change_column :merge_requests_closing_issues, :merge_request_id, :bigint
    change_column :merge_requests_closing_issues, :issue_id, :bigint
    change_column :merge_trains, :merge_request_id, :bigint
    change_column :merge_trains, :user_id, :bigint
    change_column :merge_trains, :pipeline_id, :bigint
    change_column :merge_trains, :target_project_id, :bigint
    change_column :milestones, :id, :bigint
    change_column :milestones, :project_id, :bigint
    change_column :milestones, :group_id, :bigint
    change_column :namespace_aggregation_schedules, :namespace_id, :bigint
    change_column :namespace_limits, :namespace_id, :bigint
    change_column :namespace_root_storage_statistics, :namespace_id, :bigint
    change_column :namespace_settings, :namespace_id, :bigint
    change_column :namespace_statistics, :id, :bigint
    change_column :namespace_statistics, :namespace_id, :bigint
    change_column :namespaces, :id, :bigint
    change_column :namespaces, :owner_id, :bigint
    change_column :namespaces, :parent_id, :bigint
    change_column :namespaces, :file_template_project_id, :bigint
    change_column :namespaces, :custom_project_templates_group_id, :bigint
    change_column :note_diff_files, :id, :bigint
    change_column :note_diff_files, :diff_note_id, :bigint
    change_column :notes, :id, :bigint
    change_column :notes, :author_id, :bigint
    change_column :notes, :project_id, :bigint
    change_column :notes, :noteable_id, :bigint
    change_column :notes, :updated_by_id, :bigint
    change_column :notes, :resolved_by_id, :bigint
    change_column :notification_settings, :id, :bigint
    change_column :notification_settings, :user_id, :bigint
    change_column :notification_settings, :source_id, :bigint
    change_column :oauth_access_grants, :id, :bigint
    change_column :oauth_access_grants, :resource_owner_id, :bigint
    change_column :oauth_access_grants, :application_id, :bigint
    change_column :oauth_access_tokens, :id, :bigint
    change_column :oauth_access_tokens, :resource_owner_id, :bigint
    change_column :oauth_access_tokens, :application_id, :bigint
    change_column :oauth_applications, :id, :bigint
    change_column :oauth_applications, :owner_id, :bigint
    change_column :oauth_openid_requests, :id, :bigint
    change_column :oauth_openid_requests, :access_grant_id, :bigint
    change_column :open_project_tracker_data, :service_id, :bigint
    change_column :operations_feature_flags, :project_id, :bigint
    change_column :operations_feature_flags_clients, :project_id, :bigint
    change_column :packages_build_infos, :package_id, :bigint
    change_column :packages_build_infos, :pipeline_id, :bigint
    change_column :packages_composer_cache_files, :namespace_id, :bigint
    change_column :packages_packages, :project_id, :bigint
    change_column :packages_packages, :creator_id, :bigint
    change_column :packages_tags, :package_id, :bigint
    change_column :pages_domain_acme_orders, :pages_domain_id, :bigint
    change_column :pages_domains, :id, :bigint
    change_column :pages_domains, :project_id, :bigint
    change_column :path_locks, :id, :bigint
    change_column :path_locks, :project_id, :bigint
    change_column :path_locks, :user_id, :bigint
    change_column :personal_access_tokens, :id, :bigint
    change_column :personal_access_tokens, :user_id, :bigint
    change_column :plans, :id, :bigint
    change_column :pool_repositories, :shard_id, :bigint
    change_column :pool_repositories, :source_project_id, :bigint
    #PG::InvalidTableDefinition: ERROR:  cannot alter column "project_id" because it is part of the partition key of relation "product_analytics_events_experimental"
    #change_column :product_analytics_events_experimental, :project_id, :bigint
    change_column :product_analytics_events_experimental, :txn_id, :bigint
    change_column :programming_languages, :id, :bigint
    change_column :project_alerting_settings, :project_id, :bigint
    change_column :project_aliases, :project_id, :bigint
    change_column :project_authorizations, :user_id, :bigint
    change_column :project_authorizations, :project_id, :bigint
    change_column :project_auto_devops, :id, :bigint
    change_column :project_auto_devops, :project_id, :bigint
    change_column :project_ci_cd_settings, :id, :bigint
    change_column :project_ci_cd_settings, :project_id, :bigint
    change_column :project_custom_attributes, :id, :bigint
    change_column :project_custom_attributes, :project_id, :bigint
    change_column :project_daily_statistics, :project_id, :bigint
    change_column :project_deploy_tokens, :id, :bigint
    change_column :project_deploy_tokens, :project_id, :bigint
    change_column :project_deploy_tokens, :deploy_token_id, :bigint
    change_column :project_error_tracking_settings, :project_id, :bigint
    change_column :project_feature_usages, :project_id, :bigint
    change_column :project_features, :id, :bigint
    change_column :project_features, :project_id, :bigint
    change_column :project_group_links, :id, :bigint
    change_column :project_group_links, :project_id, :bigint
    change_column :project_group_links, :group_id, :bigint
    change_column :project_import_data, :id, :bigint
    change_column :project_import_data, :project_id, :bigint
    change_column :project_incident_management_settings, :project_id, :bigint
    change_column :project_metrics_settings, :project_id, :bigint
    change_column :project_mirror_data, :id, :bigint
    change_column :project_mirror_data, :project_id, :bigint
    change_column :project_repositories, :shard_id, :bigint
    change_column :project_repositories, :project_id, :bigint
    change_column :project_repository_states, :id, :bigint
    change_column :project_repository_states, :project_id, :bigint
    change_column :project_settings, :project_id, :bigint
    change_column :project_statistics, :id, :bigint
    change_column :project_statistics, :project_id, :bigint
    change_column :project_statistics, :namespace_id, :bigint
    change_column :project_tracing_settings, :project_id, :bigint
    change_column :projects, :id, :bigint
    change_column :projects, :creator_id, :bigint
    change_column :projects, :namespace_id, :bigint
    change_column :projects, :mirror_user_id, :bigint
    change_column :projects, :marked_for_deletion_by_user_id, :bigint
    change_column :prometheus_alert_events, :project_id, :bigint
    change_column :prometheus_alert_events, :prometheus_alert_id, :bigint
    change_column :prometheus_alerts, :id, :bigint
    change_column :prometheus_alerts, :environment_id, :bigint
    change_column :prometheus_alerts, :project_id, :bigint
    change_column :prometheus_alerts, :prometheus_metric_id, :bigint
    change_column :prometheus_metrics, :id, :bigint
    change_column :prometheus_metrics, :project_id, :bigint
    change_column :protected_branch_merge_access_levels, :id, :bigint
    change_column :protected_branch_merge_access_levels, :protected_branch_id, :bigint
    change_column :protected_branch_merge_access_levels, :user_id, :bigint
    change_column :protected_branch_merge_access_levels, :group_id, :bigint
    change_column :protected_branch_push_access_levels, :id, :bigint
    change_column :protected_branch_push_access_levels, :protected_branch_id, :bigint
    change_column :protected_branch_push_access_levels, :user_id, :bigint
    change_column :protected_branch_push_access_levels, :group_id, :bigint
    change_column :protected_branch_push_access_levels, :deploy_key_id, :bigint
    change_column :protected_branch_unprotect_access_levels, :id, :bigint
    change_column :protected_branch_unprotect_access_levels, :protected_branch_id, :bigint
    change_column :protected_branch_unprotect_access_levels, :user_id, :bigint
    change_column :protected_branch_unprotect_access_levels, :group_id, :bigint
    change_column :protected_branches, :id, :bigint
    change_column :protected_branches, :project_id, :bigint
    change_column :protected_environment_deploy_access_levels, :id, :bigint
    change_column :protected_environment_deploy_access_levels, :protected_environment_id, :bigint
    change_column :protected_environment_deploy_access_levels, :user_id, :bigint
    change_column :protected_environment_deploy_access_levels, :group_id, :bigint
    change_column :protected_environments, :id, :bigint
    change_column :protected_environments, :project_id, :bigint
    change_column :protected_tag_create_access_levels, :id, :bigint
    change_column :protected_tag_create_access_levels, :protected_tag_id, :bigint
    change_column :protected_tag_create_access_levels, :user_id, :bigint
    change_column :protected_tag_create_access_levels, :group_id, :bigint
    change_column :protected_tags, :id, :bigint
    change_column :protected_tags, :project_id, :bigint
    change_column :push_event_payloads, :event_id, :bigint
    change_column :push_rules, :id, :bigint
    change_column :push_rules, :project_id, :bigint
    change_column :redirect_routes, :id, :bigint
    change_column :redirect_routes, :source_id, :bigint
    change_column :release_links, :release_id, :bigint
    change_column :releases, :id, :bigint
    change_column :releases, :project_id, :bigint
    change_column :releases, :author_id, :bigint
    change_column :remote_mirrors, :id, :bigint
    change_column :remote_mirrors, :project_id, :bigint
    change_column :repository_languages, :project_id, :bigint
    change_column :repository_languages, :programming_language_id, :bigint
    change_column :requirements, :project_id, :bigint
    change_column :requirements, :author_id, :bigint
    change_column :resource_label_events, :issue_id, :bigint
    change_column :resource_label_events, :merge_request_id, :bigint
    change_column :resource_label_events, :epic_id, :bigint
    change_column :resource_label_events, :label_id, :bigint
    change_column :resource_label_events, :user_id, :bigint
    change_column :resource_state_events, :epic_id, :bigint
    change_column :reviews, :author_id, :bigint
    change_column :reviews, :merge_request_id, :bigint
    change_column :reviews, :project_id, :bigint
    change_column :routes, :id, :bigint
    change_column :routes, :source_id, :bigint
    change_column :saml_providers, :id, :bigint
    change_column :saml_providers, :group_id, :bigint
    change_column :scim_oauth_access_tokens, :id, :bigint
    change_column :scim_oauth_access_tokens, :group_id, :bigint
    change_column :sent_notifications, :id, :bigint
    change_column :sent_notifications, :project_id, :bigint
    change_column :sent_notifications, :noteable_id, :bigint
    change_column :sent_notifications, :recipient_id, :bigint
    change_column :services, :id, :bigint
    change_column :services, :project_id, :bigint
    change_column :shards, :id, :bigint
    change_column :slack_integrations, :id, :bigint
    change_column :slack_integrations, :service_id, :bigint
    change_column :smartcard_identities, :user_id, :bigint
    change_column :snippet_user_mentions, :snippet_id, :bigint
    change_column :snippet_user_mentions, :note_id, :bigint
    change_column :snippets, :id, :bigint
    change_column :snippets, :author_id, :bigint
    change_column :snippets, :project_id, :bigint
    change_column :software_license_policies, :id, :bigint
    change_column :software_license_policies, :project_id, :bigint
    change_column :software_license_policies, :software_license_id, :bigint
    change_column :software_licenses, :id, :bigint
    change_column :spam_logs, :id, :bigint
    change_column :spam_logs, :user_id, :bigint
    change_column :sprints, :iterations_cadence_id, :bigint
    change_column :subscriptions, :id, :bigint
    change_column :subscriptions, :user_id, :bigint
    change_column :subscriptions, :subscribable_id, :bigint
    change_column :subscriptions, :project_id, :bigint
    change_column :suggestions, :note_id, :bigint
    change_column :system_note_metadata, :id, :bigint
    change_column :system_note_metadata, :note_id, :bigint
    change_column :taggings, :id, :bigint
    change_column :taggings, :tag_id, :bigint
    change_column :taggings, :taggable_id, :bigint
    change_column :taggings, :tagger_id, :bigint
    change_column :tags, :id, :bigint
    change_column :term_agreements, :id, :bigint
    change_column :term_agreements, :term_id, :bigint
    change_column :term_agreements, :user_id, :bigint
    change_column :timelogs, :id, :bigint
    change_column :timelogs, :user_id, :bigint
    change_column :timelogs, :issue_id, :bigint
    change_column :timelogs, :merge_request_id, :bigint
    change_column :timelogs, :note_id, :bigint
    change_column :timelogs, :project_id, :bigint
    change_column :todos, :id, :bigint
    change_column :todos, :user_id, :bigint
    change_column :todos, :project_id, :bigint
    change_column :todos, :target_id, :bigint
    change_column :todos, :author_id, :bigint
    change_column :todos, :note_id, :bigint
    change_column :todos, :group_id, :bigint
    change_column :trending_projects, :id, :bigint
    change_column :trending_projects, :project_id, :bigint
    change_column :u2f_registrations, :id, :bigint
    change_column :u2f_registrations, :user_id, :bigint
    change_column :uploads, :id, :bigint
    change_column :uploads, :model_id, :bigint
    change_column :user_agent_details, :id, :bigint
    change_column :user_agent_details, :subject_id, :bigint
    change_column :user_callouts, :id, :bigint
    change_column :user_callouts, :user_id, :bigint
    change_column :user_custom_attributes, :id, :bigint
    change_column :user_custom_attributes, :user_id, :bigint
    change_column :user_follow_users, :follower_id, :bigint
    change_column :user_follow_users, :followee_id, :bigint
    change_column :user_interacted_projects, :user_id, :bigint
    change_column :user_interacted_projects, :project_id, :bigint
    change_column :user_preferences, :id, :bigint
    change_column :user_preferences, :user_id, :bigint
    change_column :user_statuses, :user_id, :bigint
    change_column :user_synced_attributes_metadata, :id, :bigint
    change_column :user_synced_attributes_metadata, :user_id, :bigint
    change_column :users, :id, :bigint
    change_column :users, :color_scheme_id, :bigint
    change_column :users, :created_by_id, :bigint
    change_column :users, :email_opted_in_source_id, :bigint
    change_column :users, :accepted_term_id, :bigint
    change_column :users, :managing_group_id, :bigint
    change_column :users_ops_dashboard_projects, :user_id, :bigint
    change_column :users_ops_dashboard_projects, :project_id, :bigint
    change_column :users_star_projects, :id, :bigint
    change_column :users_star_projects, :project_id, :bigint
    change_column :users_star_projects, :user_id, :bigint
    change_column :vulnerability_exports, :group_id, :bigint
    change_column :vulnerability_feedback, :id, :bigint
    change_column :vulnerability_feedback, :project_id, :bigint
    change_column :vulnerability_feedback, :author_id, :bigint
    change_column :vulnerability_feedback, :pipeline_id, :bigint
    change_column :vulnerability_feedback, :issue_id, :bigint
    change_column :vulnerability_feedback, :merge_request_id, :bigint
    change_column :vulnerability_feedback, :comment_author_id, :bigint
    change_column :vulnerability_identifiers, :project_id, :bigint
    change_column :vulnerability_occurrence_pipelines, :pipeline_id, :bigint
    change_column :vulnerability_occurrences, :project_id, :bigint
    change_column :vulnerability_scanners, :project_id, :bigint
    change_column :vulnerability_user_mentions, :note_id, :bigint
    change_column :web_hook_logs, :web_hook_id, :bigint
    change_column :web_hook_logs_archived, :id, :bigint
    change_column :web_hook_logs_archived, :web_hook_id, :bigint
    change_column :web_hooks, :id, :bigint
    change_column :web_hooks, :project_id, :bigint
    change_column :web_hooks, :service_id, :bigint
    change_column :web_hooks, :group_id, :bigint
    change_column :webauthn_registrations, :u2f_registration_id, :bigint
    change_column :wiki_page_meta, :id, :bigint
    change_column :wiki_page_slugs, :id, :bigint

    execute <<-EOS
      CREATE TRIGGER trigger_has_external_issue_tracker_on_delete AFTER DELETE ON services FOR EACH ROW WHEN ((((old.category)::text = 'issue_tracker'::text) AND (old.active = true) AND (old.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_issue_tracker();
      CREATE TRIGGER trigger_has_external_issue_tracker_on_insert AFTER INSERT ON services FOR EACH ROW WHEN ((((new.category)::text = 'issue_tracker'::text) AND (new.active = true) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_issue_tracker();
      CREATE TRIGGER trigger_has_external_issue_tracker_on_update AFTER UPDATE ON services FOR EACH ROW WHEN ((((new.category)::text = 'issue_tracker'::text) AND (old.active <> new.active) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_issue_tracker();
      CREATE TRIGGER trigger_has_external_wiki_on_delete AFTER DELETE ON services FOR EACH ROW WHEN ((((old.type)::text = 'ExternalWikiService'::text) AND (old.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_wiki();
      CREATE TRIGGER trigger_has_external_wiki_on_insert AFTER INSERT ON services FOR EACH ROW WHEN (((new.active = true) AND ((new.type)::text = 'ExternalWikiService'::text) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_wiki();
      CREATE TRIGGER trigger_has_external_wiki_on_update AFTER UPDATE ON services FOR EACH ROW WHEN ((((new.type)::text = 'ExternalWikiService'::text) AND (old.active <> new.active) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_wiki();
    EOS
  end
  
  def down
    execute <<-EOS
      DROP TRIGGER IF EXISTS trigger_has_external_issue_tracker_on_delete ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_issue_tracker_on_insert ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_issue_tracker_on_update ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_wiki_on_delete ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_wiki_on_insert ON services;
      DROP TRIGGER IF EXISTS trigger_has_external_wiki_on_update ON services;
    EOS

    change_column :abuse_reports, :id, :integer
    change_column :abuse_reports, :reporter_id, :integer
    change_column :abuse_reports, :user_id, :integer
    change_column :alert_management_alerts, :prometheus_alert_id, :integer
    change_column :alert_management_alerts, :environment_id, :integer
    change_column :allowed_email_domains, :group_id, :integer
    change_column :analytics_devops_adoption_segments, :namespace_id, :integer
    change_column :appearances, :id, :integer
    change_column :application_setting_terms, :id, :integer
    change_column :application_settings, :id, :integer
    change_column :application_settings, :performance_bar_allowed_group_id, :integer
    change_column :application_settings, :file_template_project_id, :integer
    change_column :application_settings, :custom_project_templates_group_id, :integer
    change_column :application_settings, :usage_stats_set_by_user_id, :integer
    change_column :application_settings, :instance_administrators_group_id, :integer
    change_column :approval_merge_request_rules, :merge_request_id, :integer
    change_column :approval_merge_request_rules_approved_approvers, :user_id, :integer
    change_column :approval_merge_request_rules_groups, :group_id, :integer
    change_column :approval_merge_request_rules_users, :user_id, :integer
    change_column :approval_project_rules, :project_id, :integer
    change_column :approval_project_rules_groups, :group_id, :integer
    change_column :approval_project_rules_users, :user_id, :integer
    change_column :approvals, :id, :integer
    change_column :approvals, :merge_request_id, :integer
    change_column :approvals, :user_id, :integer
    change_column :approver_groups, :id, :integer
    change_column :approver_groups, :target_id, :integer
    change_column :approver_groups, :group_id, :integer
    change_column :approvers, :id, :integer
    change_column :approvers, :target_id, :integer
    change_column :approvers, :user_id, :integer
    change_column :audit_events, :author_id, :integer
    change_column :audit_events, :entity_id, :integer
    change_column :award_emoji, :id, :integer
    change_column :award_emoji, :user_id, :integer
    change_column :award_emoji, :awardable_id, :integer
    change_column :aws_roles, :user_id, :integer
    change_column :badges, :id, :integer
    change_column :badges, :project_id, :integer
    change_column :badges, :group_id, :integer
    change_column :board_assignees, :id, :integer
    change_column :board_assignees, :board_id, :integer
    change_column :board_assignees, :assignee_id, :integer
    change_column :board_group_recent_visits, :user_id, :integer
    change_column :board_group_recent_visits, :board_id, :integer
    change_column :board_group_recent_visits, :group_id, :integer
    change_column :board_labels, :id, :integer
    change_column :board_labels, :board_id, :integer
    change_column :board_labels, :label_id, :integer
    change_column :board_project_recent_visits, :user_id, :integer
    change_column :board_project_recent_visits, :project_id, :integer
    change_column :board_project_recent_visits, :board_id, :integer
    change_column :boards, :id, :integer
    change_column :boards, :project_id, :integer
    change_column :boards, :milestone_id, :integer
    change_column :boards, :group_id, :integer
    change_column :broadcast_messages, :id, :integer
    change_column :bulk_import_configurations, :bulk_import_id, :integer
    change_column :bulk_imports, :user_id, :integer
    change_column :chat_names, :id, :integer
    change_column :chat_names, :user_id, :integer
    change_column :chat_names, :service_id, :integer
    change_column :chat_teams, :id, :integer
    change_column :chat_teams, :namespace_id, :integer
    change_column :ci_build_needs, :id, :integer
    change_column :ci_build_needs, :build_id, :integer
    change_column :ci_build_trace_chunks, :build_id, :integer
    change_column :ci_build_trace_section_names, :id, :integer
    change_column :ci_build_trace_section_names, :project_id, :integer
    change_column :ci_build_trace_sections, :project_id, :integer
    change_column :ci_build_trace_sections, :build_id, :integer
    change_column :ci_build_trace_sections, :section_name_id, :integer
    change_column :ci_builds, :id, :integer
    change_column :ci_builds, :runner_id, :integer
    change_column :ci_builds, :commit_id, :integer
    change_column :ci_builds, :trigger_request_id, :integer
    change_column :ci_builds, :user_id, :integer
    change_column :ci_builds, :project_id, :integer
    change_column :ci_builds, :erased_by_id, :integer
    change_column :ci_builds, :auto_canceled_by_id, :integer
    change_column :ci_builds, :stage_id, :integer
    change_column :ci_builds, :upstream_pipeline_id, :integer
    change_column :ci_builds_metadata, :id, :integer
    change_column :ci_builds_metadata, :build_id, :integer
    change_column :ci_builds_metadata, :project_id, :integer
    change_column :ci_builds_runner_session, :build_id, :integer
    change_column :ci_group_variables, :id, :integer
    change_column :ci_group_variables, :group_id, :integer
    change_column :ci_job_artifacts, :id, :integer
    change_column :ci_job_artifacts, :project_id, :integer
    change_column :ci_job_artifacts, :job_id, :integer
    change_column :ci_pipeline_chat_data, :pipeline_id, :integer
    change_column :ci_pipeline_chat_data, :chat_name_id, :integer
    change_column :ci_pipeline_messages, :pipeline_id, :integer
    change_column :ci_pipeline_schedule_variables, :id, :integer
    change_column :ci_pipeline_schedule_variables, :pipeline_schedule_id, :integer
    change_column :ci_pipeline_schedules, :id, :integer
    change_column :ci_pipeline_schedules, :project_id, :integer
    change_column :ci_pipeline_schedules, :owner_id, :integer
    change_column :ci_pipeline_variables, :id, :integer
    change_column :ci_pipeline_variables, :pipeline_id, :integer
    change_column :ci_pipelines, :id, :integer
    change_column :ci_pipelines, :project_id, :integer
    change_column :ci_pipelines, :user_id, :integer
    change_column :ci_pipelines, :auto_canceled_by_id, :integer
    change_column :ci_pipelines, :pipeline_schedule_id, :integer
    change_column :ci_pipelines, :merge_request_id, :integer
    change_column :ci_runner_namespaces, :id, :integer
    change_column :ci_runner_namespaces, :runner_id, :integer
    change_column :ci_runner_namespaces, :namespace_id, :integer
    change_column :ci_runner_projects, :id, :integer
    change_column :ci_runner_projects, :runner_id, :integer
    change_column :ci_runner_projects, :project_id, :integer
    change_column :ci_runners, :id, :integer
    change_column :ci_sources_pipelines, :id, :integer
    change_column :ci_sources_pipelines, :project_id, :integer
    change_column :ci_sources_pipelines, :pipeline_id, :integer
    change_column :ci_sources_pipelines, :source_project_id, :integer
    change_column :ci_sources_pipelines, :source_job_id, :integer
    change_column :ci_sources_pipelines, :source_pipeline_id, :integer
    change_column :ci_stages, :id, :integer
    change_column :ci_stages, :project_id, :integer
    change_column :ci_stages, :pipeline_id, :integer
    change_column :ci_trigger_requests, :id, :integer
    change_column :ci_trigger_requests, :trigger_id, :integer
    change_column :ci_trigger_requests, :commit_id, :integer
    change_column :ci_triggers, :id, :integer
    change_column :ci_triggers, :project_id, :integer
    change_column :ci_triggers, :owner_id, :integer
    change_column :ci_variables, :id, :integer
    change_column :ci_variables, :project_id, :integer
    change_column :cluster_groups, :id, :integer
    change_column :cluster_groups, :cluster_id, :integer
    change_column :cluster_groups, :group_id, :integer
    change_column :cluster_platforms_kubernetes, :id, :integer
    change_column :cluster_platforms_kubernetes, :cluster_id, :integer
    change_column :cluster_projects, :id, :integer
    change_column :cluster_projects, :project_id, :integer
    change_column :cluster_projects, :cluster_id, :integer
    change_column :cluster_providers_gcp, :id, :integer
    change_column :cluster_providers_gcp, :cluster_id, :integer
    change_column :clusters, :id, :integer
    change_column :clusters, :user_id, :integer
    change_column :clusters, :management_project_id, :integer
    change_column :clusters_applications_cert_managers, :id, :integer
    change_column :clusters_applications_cert_managers, :cluster_id, :integer
    change_column :clusters_applications_crossplane, :id, :integer
    change_column :clusters_applications_helm, :id, :integer
    change_column :clusters_applications_helm, :cluster_id, :integer
    change_column :clusters_applications_ingress, :id, :integer
    change_column :clusters_applications_ingress, :cluster_id, :integer
    change_column :clusters_applications_jupyter, :id, :integer
    change_column :clusters_applications_jupyter, :cluster_id, :integer
    change_column :clusters_applications_jupyter, :oauth_application_id, :integer
    change_column :clusters_applications_knative, :id, :integer
    change_column :clusters_applications_knative, :cluster_id, :integer
    change_column :clusters_applications_prometheus, :id, :integer
    change_column :clusters_applications_prometheus, :cluster_id, :integer
    change_column :clusters_applications_runners, :id, :integer
    change_column :clusters_applications_runners, :cluster_id, :integer
    change_column :clusters_applications_runners, :runner_id, :integer
    change_column :clusters_kubernetes_namespaces, :cluster_id, :integer
    change_column :clusters_kubernetes_namespaces, :project_id, :integer
    change_column :clusters_kubernetes_namespaces, :cluster_project_id, :integer
    change_column :commit_user_mentions, :note_id, :integer
    change_column :compliance_management_frameworks, :namespace_id, :integer
    change_column :container_repositories, :id, :integer
    change_column :container_repositories, :project_id, :integer
    change_column :conversational_development_index_metrics, :id, :integer
    change_column :dast_scanner_profiles, :project_id, :integer
    change_column :dependency_proxy_blobs, :id, :integer
    change_column :dependency_proxy_blobs, :group_id, :integer
    change_column :dependency_proxy_group_settings, :id, :integer
    change_column :dependency_proxy_group_settings, :group_id, :integer
    change_column :deploy_keys_projects, :id, :integer
    change_column :deploy_keys_projects, :deploy_key_id, :integer
    change_column :deploy_keys_projects, :project_id, :integer
    change_column :deploy_tokens, :id, :integer
    change_column :deployment_clusters, :deployment_id, :integer
    change_column :deployment_clusters, :cluster_id, :integer
    change_column :deployment_merge_requests, :deployment_id, :integer
    change_column :deployment_merge_requests, :merge_request_id, :integer
    change_column :deployment_merge_requests, :environment_id, :integer
    change_column :deployments, :id, :integer
    change_column :deployments, :project_id, :integer
    change_column :deployments, :environment_id, :integer
    change_column :deployments, :user_id, :integer
    change_column :deployments, :deployable_id, :integer
    change_column :deployments, :cluster_id, :integer
    change_column :description_versions, :issue_id, :integer
    change_column :description_versions, :merge_request_id, :integer
    change_column :description_versions, :epic_id, :integer
    change_column :design_management_designs, :project_id, :integer
    change_column :design_management_designs, :issue_id, :integer
    change_column :design_management_versions, :author_id, :integer
    change_column :design_user_mentions, :design_id, :integer
    change_column :design_user_mentions, :note_id, :integer
    change_column :draft_notes, :merge_request_id, :integer
    change_column :draft_notes, :author_id, :integer
    change_column :elasticsearch_indexed_namespaces, :namespace_id, :integer
    change_column :elasticsearch_indexed_projects, :project_id, :integer
    change_column :emails, :id, :integer
    change_column :emails, :user_id, :integer
    change_column :environments, :id, :integer
    change_column :environments, :project_id, :integer
    change_column :epic_issues, :id, :integer
    change_column :epic_issues, :epic_id, :integer
    change_column :epic_issues, :issue_id, :integer
    change_column :epic_metrics, :id, :integer
    change_column :epic_metrics, :epic_id, :integer
    change_column :epic_user_mentions, :epic_id, :integer
    change_column :epic_user_mentions, :note_id, :integer
    change_column :epics, :id, :integer
    change_column :epics, :group_id, :integer
    change_column :epics, :author_id, :integer
    change_column :epics, :assignee_id, :integer
    change_column :epics, :updated_by_id, :integer
    change_column :epics, :last_edited_by_id, :integer
    change_column :epics, :start_date_sourcing_milestone_id, :integer
    change_column :epics, :due_date_sourcing_milestone_id, :integer
    change_column :epics, :closed_by_id, :integer
    change_column :epics, :parent_id, :integer
    change_column :epics, :start_date_sourcing_epic_id, :integer
    change_column :epics, :due_date_sourcing_epic_id, :integer
    change_column :events, :id, :integer
    change_column :events, :project_id, :integer
    change_column :events, :author_id, :integer
    change_column :events, :target_id, :integer
    change_column :feature_gates, :id, :integer
    change_column :features, :id, :integer
    change_column :fork_network_members, :id, :integer
    change_column :fork_network_members, :fork_network_id, :integer
    change_column :fork_network_members, :project_id, :integer
    change_column :fork_network_members, :forked_from_project_id, :integer
    change_column :fork_networks, :id, :integer
    change_column :fork_networks, :root_project_id, :integer
    change_column :geo_container_repository_updated_events, :container_repository_id, :integer
    change_column :geo_event_log, :geo_event_id, :integer
    change_column :geo_hashed_storage_attachments_events, :project_id, :integer
    change_column :geo_hashed_storage_migrated_events, :project_id, :integer
    change_column :geo_job_artifact_deleted_events, :job_artifact_id, :integer
    change_column :geo_lfs_object_deleted_events, :lfs_object_id, :integer
    change_column :geo_node_namespace_links, :id, :integer
    change_column :geo_node_namespace_links, :geo_node_id, :integer
    change_column :geo_node_namespace_links, :namespace_id, :integer
    change_column :geo_node_statuses, :id, :integer
    change_column :geo_node_statuses, :geo_node_id, :integer
    change_column :geo_node_statuses, :last_event_id, :integer
    change_column :geo_node_statuses, :cursor_last_event_id, :integer
    change_column :geo_nodes, :id, :integer
    change_column :geo_nodes, :oauth_application_id, :integer
    change_column :geo_repositories_changed_events, :geo_node_id, :integer
    change_column :geo_repository_created_events, :project_id, :integer
    change_column :geo_repository_deleted_events, :project_id, :integer
    change_column :geo_repository_renamed_events, :project_id, :integer
    change_column :geo_repository_updated_events, :project_id, :integer
    change_column :geo_reset_checksum_events, :project_id, :integer
    change_column :geo_upload_deleted_events, :upload_id, :integer
    change_column :geo_upload_deleted_events, :model_id, :integer
    change_column :gitlab_subscription_histories, :namespace_id, :integer
    change_column :gitlab_subscription_histories, :hosted_plan_id, :integer
    change_column :gitlab_subscriptions, :namespace_id, :integer
    change_column :gitlab_subscriptions, :hosted_plan_id, :integer
    change_column :gpg_key_subkeys, :id, :integer
    change_column :gpg_key_subkeys, :gpg_key_id, :integer
    change_column :gpg_keys, :id, :integer
    change_column :gpg_keys, :user_id, :integer
    change_column :gpg_signatures, :id, :integer
    change_column :gpg_signatures, :project_id, :integer
    change_column :gpg_signatures, :gpg_key_id, :integer
    change_column :gpg_signatures, :gpg_key_subkey_id, :integer
    change_column :group_custom_attributes, :id, :integer
    change_column :group_custom_attributes, :group_id, :integer
    change_column :historical_data, :id, :integer
    change_column :identities, :id, :integer
    change_column :identities, :user_id, :integer
    change_column :identities, :saml_provider_id, :integer
    change_column :import_export_uploads, :id, :integer
    change_column :import_export_uploads, :project_id, :integer
    change_column :import_failures, :group_id, :integer
    change_column :index_statuses, :id, :integer
    change_column :index_statuses, :project_id, :integer
    change_column :insights, :id, :integer
    change_column :insights, :namespace_id, :integer
    change_column :insights, :project_id, :integer
    change_column :internal_ids, :project_id, :integer
    change_column :internal_ids, :namespace_id, :integer
    change_column :ip_restrictions, :group_id, :integer
    change_column :issue_assignees, :user_id, :integer
    change_column :issue_assignees, :issue_id, :integer
    change_column :issue_links, :id, :integer
    change_column :issue_links, :source_id, :integer
    change_column :issue_links, :target_id, :integer
    change_column :issue_metrics, :id, :integer
    change_column :issue_metrics, :issue_id, :integer
    change_column :issue_tracker_data, :service_id, :integer
    change_column :issue_user_mentions, :issue_id, :integer
    change_column :issue_user_mentions, :note_id, :integer
    change_column :issues, :id, :integer
    change_column :issues, :author_id, :integer
    change_column :issues, :project_id, :integer
    change_column :issues, :milestone_id, :integer
    change_column :issues, :updated_by_id, :integer
    change_column :issues, :moved_to_id, :integer
    change_column :issues, :last_edited_by_id, :integer
    change_column :issues, :closed_by_id, :integer
    change_column :issues, :duplicated_to_id, :integer
    change_column :issues, :promoted_to_epic_id, :integer
    change_column :jira_connect_subscriptions, :namespace_id, :integer
    change_column :jira_tracker_data, :service_id, :integer
    change_column :keys, :id, :integer
    change_column :keys, :user_id, :integer
    change_column :label_links, :id, :integer
    change_column :label_links, :label_id, :integer
    change_column :label_links, :target_id, :integer
    change_column :label_priorities, :id, :integer
    change_column :label_priorities, :project_id, :integer
    change_column :label_priorities, :label_id, :integer
    change_column :labels, :id, :integer
    change_column :labels, :project_id, :integer
    change_column :labels, :group_id, :integer
    change_column :ldap_group_links, :id, :integer
    change_column :ldap_group_links, :group_id, :integer
    change_column :lfs_file_locks, :id, :integer
    change_column :lfs_file_locks, :project_id, :integer
    change_column :lfs_file_locks, :user_id, :integer
    change_column :lfs_objects, :id, :integer
    change_column :lfs_objects_projects, :id, :integer
    change_column :lfs_objects_projects, :lfs_object_id, :integer
    change_column :lfs_objects_projects, :project_id, :integer
    change_column :licenses, :id, :integer
    change_column :lists, :id, :integer
    change_column :lists, :board_id, :integer
    change_column :lists, :label_id, :integer
    change_column :lists, :user_id, :integer
    change_column :lists, :milestone_id, :integer
    change_column :members, :id, :integer
    change_column :members, :source_id, :integer
    change_column :members, :user_id, :integer
    change_column :members, :created_by_id, :integer
    change_column :merge_request_assignees, :user_id, :integer
    change_column :merge_request_assignees, :merge_request_id, :integer
    change_column :merge_request_blocks, :blocking_merge_request_id, :integer
    change_column :merge_request_blocks, :blocked_merge_request_id, :integer
    change_column :merge_request_diff_commits, :merge_request_diff_id, :integer
    change_column :merge_request_diff_files, :merge_request_diff_id, :integer
    change_column :merge_request_diffs, :id, :integer
    change_column :merge_request_diffs, :merge_request_id, :integer
    change_column :merge_request_metrics, :id, :integer
    change_column :merge_request_metrics, :merge_request_id, :integer
    change_column :merge_request_metrics, :pipeline_id, :integer
    change_column :merge_request_metrics, :merged_by_id, :integer
    change_column :merge_request_metrics, :latest_closed_by_id, :integer
    change_column :merge_request_metrics, :target_project_id, :integer
    change_column :merge_request_user_mentions, :merge_request_id, :integer
    change_column :merge_request_user_mentions, :note_id, :integer
    change_column :merge_requests, :id, :integer
    change_column :merge_requests, :source_project_id, :integer
    change_column :merge_requests, :author_id, :integer
    change_column :merge_requests, :assignee_id, :integer
    change_column :merge_requests, :milestone_id, :integer
    change_column :merge_requests, :target_project_id, :integer
    change_column :merge_requests, :updated_by_id, :integer
    change_column :merge_requests, :merge_user_id, :integer
    change_column :merge_requests, :last_edited_by_id, :integer
    change_column :merge_requests, :head_pipeline_id, :integer
    change_column :merge_requests, :latest_merge_request_diff_id, :integer
    change_column :merge_requests_closing_issues, :id, :integer
    change_column :merge_requests_closing_issues, :merge_request_id, :integer
    change_column :merge_requests_closing_issues, :issue_id, :integer
    change_column :merge_trains, :merge_request_id, :integer
    change_column :merge_trains, :user_id, :integer
    change_column :merge_trains, :pipeline_id, :integer
    change_column :merge_trains, :target_project_id, :integer
    change_column :milestones, :id, :integer
    change_column :milestones, :project_id, :integer
    change_column :milestones, :group_id, :integer
    change_column :namespace_aggregation_schedules, :namespace_id, :integer
    change_column :namespace_limits, :namespace_id, :integer
    change_column :namespace_root_storage_statistics, :namespace_id, :integer
    change_column :namespace_settings, :namespace_id, :integer
    change_column :namespace_statistics, :id, :integer
    change_column :namespace_statistics, :namespace_id, :integer
    change_column :namespaces, :id, :integer
    change_column :namespaces, :owner_id, :integer
    change_column :namespaces, :parent_id, :integer
    change_column :namespaces, :file_template_project_id, :integer
    change_column :namespaces, :custom_project_templates_group_id, :integer
    change_column :note_diff_files, :id, :integer
    change_column :note_diff_files, :diff_note_id, :integer
    change_column :notes, :id, :integer
    change_column :notes, :author_id, :integer
    change_column :notes, :project_id, :integer
    change_column :notes, :noteable_id, :integer
    change_column :notes, :updated_by_id, :integer
    change_column :notes, :resolved_by_id, :integer
    change_column :notification_settings, :id, :integer
    change_column :notification_settings, :user_id, :integer
    change_column :notification_settings, :source_id, :integer
    change_column :oauth_access_grants, :id, :integer
    change_column :oauth_access_grants, :resource_owner_id, :integer
    change_column :oauth_access_grants, :application_id, :integer
    change_column :oauth_access_tokens, :id, :integer
    change_column :oauth_access_tokens, :resource_owner_id, :integer
    change_column :oauth_access_tokens, :application_id, :integer
    change_column :oauth_applications, :id, :integer
    change_column :oauth_applications, :owner_id, :integer
    change_column :oauth_openid_requests, :id, :integer
    change_column :oauth_openid_requests, :access_grant_id, :integer
    change_column :open_project_tracker_data, :service_id, :integer
    change_column :operations_feature_flags, :project_id, :integer
    change_column :operations_feature_flags_clients, :project_id, :integer
    change_column :packages_build_infos, :package_id, :integer
    change_column :packages_build_infos, :pipeline_id, :integer
    change_column :packages_composer_cache_files, :namespace_id, :integer
    change_column :packages_packages, :project_id, :integer
    change_column :packages_packages, :creator_id, :integer
    change_column :packages_tags, :package_id, :integer
    change_column :pages_domain_acme_orders, :pages_domain_id, :integer
    change_column :pages_domains, :id, :integer
    change_column :pages_domains, :project_id, :integer
    change_column :parts, :id, :integer
    change_column :parts, :part_id, :integer
    change_column :parts_p1, :id, :integer
    change_column :parts_p1, :part_id, :integer
    change_column :parts_p2, :id, :integer
    change_column :parts_p2, :part_id, :integer
    change_column :parts_pd, :id, :integer
    change_column :parts_pd, :part_id, :integer
    change_column :path_locks, :id, :integer
    change_column :path_locks, :project_id, :integer
    change_column :path_locks, :user_id, :integer
    change_column :personal_access_tokens, :id, :integer
    change_column :personal_access_tokens, :user_id, :integer
    change_column :plans, :id, :integer
    change_column :pool_repositories, :shard_id, :integer
    change_column :pool_repositories, :source_project_id, :integer
    change_column :product_analytics_events_experimental, :project_id, :integer
    change_column :product_analytics_events_experimental, :txn_id, :integer
    change_column :programming_languages, :id, :integer
    change_column :project_alerting_settings, :project_id, :integer
    change_column :project_aliases, :project_id, :integer
    change_column :project_authorizations, :user_id, :integer
    change_column :project_authorizations, :project_id, :integer
    change_column :project_auto_devops, :id, :integer
    change_column :project_auto_devops, :project_id, :integer
    change_column :project_ci_cd_settings, :id, :integer
    change_column :project_ci_cd_settings, :project_id, :integer
    change_column :project_custom_attributes, :id, :integer
    change_column :project_custom_attributes, :project_id, :integer
    change_column :project_daily_statistics, :project_id, :integer
    change_column :project_deploy_tokens, :id, :integer
    change_column :project_deploy_tokens, :project_id, :integer
    change_column :project_deploy_tokens, :deploy_token_id, :integer
    change_column :project_error_tracking_settings, :project_id, :integer
    change_column :project_feature_usages, :project_id, :integer
    change_column :project_features, :id, :integer
    change_column :project_features, :project_id, :integer
    change_column :project_group_links, :id, :integer
    change_column :project_group_links, :project_id, :integer
    change_column :project_group_links, :group_id, :integer
    change_column :project_import_data, :id, :integer
    change_column :project_import_data, :project_id, :integer
    change_column :project_incident_management_settings, :project_id, :integer
    change_column :project_metrics_settings, :project_id, :integer
    change_column :project_mirror_data, :id, :integer
    change_column :project_mirror_data, :project_id, :integer
    change_column :project_repositories, :shard_id, :integer
    change_column :project_repositories, :project_id, :integer
    change_column :project_repository_states, :id, :integer
    change_column :project_repository_states, :project_id, :integer
    change_column :project_settings, :project_id, :integer
    change_column :project_statistics, :id, :integer
    change_column :project_statistics, :project_id, :integer
    change_column :project_statistics, :namespace_id, :integer
    change_column :project_tracing_settings, :project_id, :integer
    change_column :projects, :id, :integer
    change_column :projects, :creator_id, :integer
    change_column :projects, :namespace_id, :integer
    change_column :projects, :mirror_user_id, :integer
    change_column :projects, :marked_for_deletion_by_user_id, :integer
    change_column :prometheus_alert_events, :project_id, :integer
    change_column :prometheus_alert_events, :prometheus_alert_id, :integer
    change_column :prometheus_alerts, :id, :integer
    change_column :prometheus_alerts, :environment_id, :integer
    change_column :prometheus_alerts, :project_id, :integer
    change_column :prometheus_alerts, :prometheus_metric_id, :integer
    change_column :prometheus_metrics, :id, :integer
    change_column :prometheus_metrics, :project_id, :integer
    change_column :protected_branch_merge_access_levels, :id, :integer
    change_column :protected_branch_merge_access_levels, :protected_branch_id, :integer
    change_column :protected_branch_merge_access_levels, :user_id, :integer
    change_column :protected_branch_merge_access_levels, :group_id, :integer
    change_column :protected_branch_push_access_levels, :id, :integer
    change_column :protected_branch_push_access_levels, :protected_branch_id, :integer
    change_column :protected_branch_push_access_levels, :user_id, :integer
    change_column :protected_branch_push_access_levels, :group_id, :integer
    change_column :protected_branch_push_access_levels, :deploy_key_id, :integer
    change_column :protected_branch_unprotect_access_levels, :id, :integer
    change_column :protected_branch_unprotect_access_levels, :protected_branch_id, :integer
    change_column :protected_branch_unprotect_access_levels, :user_id, :integer
    change_column :protected_branch_unprotect_access_levels, :group_id, :integer
    change_column :protected_branches, :id, :integer
    change_column :protected_branches, :project_id, :integer
    change_column :protected_environment_deploy_access_levels, :id, :integer
    change_column :protected_environment_deploy_access_levels, :protected_environment_id, :integer
    change_column :protected_environment_deploy_access_levels, :user_id, :integer
    change_column :protected_environment_deploy_access_levels, :group_id, :integer
    change_column :protected_environments, :id, :integer
    change_column :protected_environments, :project_id, :integer
    change_column :protected_tag_create_access_levels, :id, :integer
    change_column :protected_tag_create_access_levels, :protected_tag_id, :integer
    change_column :protected_tag_create_access_levels, :user_id, :integer
    change_column :protected_tag_create_access_levels, :group_id, :integer
    change_column :protected_tags, :id, :integer
    change_column :protected_tags, :project_id, :integer
    change_column :push_event_payloads, :event_id, :integer
    change_column :push_rules, :id, :integer
    change_column :push_rules, :project_id, :integer
    change_column :redirect_routes, :id, :integer
    change_column :redirect_routes, :source_id, :integer
    change_column :release_links, :release_id, :integer
    change_column :releases, :id, :integer
    change_column :releases, :project_id, :integer
    change_column :releases, :author_id, :integer
    change_column :remote_mirrors, :id, :integer
    change_column :remote_mirrors, :project_id, :integer
    change_column :repository_languages, :project_id, :integer
    change_column :repository_languages, :programming_language_id, :integer
    change_column :requirements, :project_id, :integer
    change_column :requirements, :author_id, :integer
    change_column :resource_label_events, :issue_id, :integer
    change_column :resource_label_events, :merge_request_id, :integer
    change_column :resource_label_events, :epic_id, :integer
    change_column :resource_label_events, :label_id, :integer
    change_column :resource_label_events, :user_id, :integer
    change_column :resource_state_events, :epic_id, :integer
    change_column :reviews, :author_id, :integer
    change_column :reviews, :merge_request_id, :integer
    change_column :reviews, :project_id, :integer
    change_column :routes, :id, :integer
    change_column :routes, :source_id, :integer
    change_column :saml_providers, :id, :integer
    change_column :saml_providers, :group_id, :integer
    change_column :scim_oauth_access_tokens, :id, :integer
    change_column :scim_oauth_access_tokens, :group_id, :integer
    change_column :sent_notifications, :id, :integer
    change_column :sent_notifications, :project_id, :integer
    change_column :sent_notifications, :noteable_id, :integer
    change_column :sent_notifications, :recipient_id, :integer
    change_column :services, :id, :integer
    change_column :services, :project_id, :integer
    change_column :shards, :id, :integer
    change_column :slack_integrations, :id, :integer
    change_column :slack_integrations, :service_id, :integer
    change_column :smartcard_identities, :user_id, :integer
    change_column :snippet_user_mentions, :snippet_id, :integer
    change_column :snippet_user_mentions, :note_id, :integer
    change_column :snippets, :id, :integer
    change_column :snippets, :author_id, :integer
    change_column :snippets, :project_id, :integer
    change_column :software_license_policies, :id, :integer
    change_column :software_license_policies, :project_id, :integer
    change_column :software_license_policies, :software_license_id, :integer
    change_column :software_licenses, :id, :integer
    change_column :spam_logs, :id, :integer
    change_column :spam_logs, :user_id, :integer
    change_column :sprints, :iterations_cadence_id, :integer
    change_column :subscriptions, :id, :integer
    change_column :subscriptions, :user_id, :integer
    change_column :subscriptions, :subscribable_id, :integer
    change_column :subscriptions, :project_id, :integer
    change_column :suggestions, :note_id, :integer
    change_column :system_note_metadata, :id, :integer
    change_column :system_note_metadata, :note_id, :integer
    change_column :taggings, :id, :integer
    change_column :taggings, :tag_id, :integer
    change_column :taggings, :taggable_id, :integer
    change_column :taggings, :tagger_id, :integer
    change_column :tags, :id, :integer
    change_column :term_agreements, :id, :integer
    change_column :term_agreements, :term_id, :integer
    change_column :term_agreements, :user_id, :integer
    change_column :timelogs, :id, :integer
    change_column :timelogs, :user_id, :integer
    change_column :timelogs, :issue_id, :integer
    change_column :timelogs, :merge_request_id, :integer
    change_column :timelogs, :note_id, :integer
    change_column :timelogs, :project_id, :integer
    change_column :todos, :id, :integer
    change_column :todos, :user_id, :integer
    change_column :todos, :project_id, :integer
    change_column :todos, :target_id, :integer
    change_column :todos, :author_id, :integer
    change_column :todos, :note_id, :integer
    change_column :todos, :group_id, :integer
    change_column :trending_projects, :id, :integer
    change_column :trending_projects, :project_id, :integer
    change_column :u2f_registrations, :id, :integer
    change_column :u2f_registrations, :user_id, :integer
    change_column :uploads, :id, :integer
    change_column :uploads, :model_id, :integer
    change_column :user_agent_details, :id, :integer
    change_column :user_agent_details, :subject_id, :integer
    change_column :user_callouts, :id, :integer
    change_column :user_callouts, :user_id, :integer
    change_column :user_custom_attributes, :id, :integer
    change_column :user_custom_attributes, :user_id, :integer
    change_column :user_follow_users, :follower_id, :integer
    change_column :user_follow_users, :followee_id, :integer
    change_column :user_interacted_projects, :user_id, :integer
    change_column :user_interacted_projects, :project_id, :integer
    change_column :user_preferences, :id, :integer
    change_column :user_preferences, :user_id, :integer
    change_column :user_statuses, :user_id, :integer
    change_column :user_synced_attributes_metadata, :id, :integer
    change_column :user_synced_attributes_metadata, :user_id, :integer
    change_column :users, :id, :integer
    change_column :users, :color_scheme_id, :integer
    change_column :users, :created_by_id, :integer
    change_column :users, :email_opted_in_source_id, :integer
    change_column :users, :accepted_term_id, :integer
    change_column :users, :managing_group_id, :integer
    change_column :users_ops_dashboard_projects, :user_id, :integer
    change_column :users_ops_dashboard_projects, :project_id, :integer
    change_column :users_star_projects, :id, :integer
    change_column :users_star_projects, :project_id, :integer
    change_column :users_star_projects, :user_id, :integer
    change_column :vulnerability_exports, :group_id, :integer
    change_column :vulnerability_feedback, :id, :integer
    change_column :vulnerability_feedback, :project_id, :integer
    change_column :vulnerability_feedback, :author_id, :integer
    change_column :vulnerability_feedback, :pipeline_id, :integer
    change_column :vulnerability_feedback, :issue_id, :integer
    change_column :vulnerability_feedback, :merge_request_id, :integer
    change_column :vulnerability_feedback, :comment_author_id, :integer
    change_column :vulnerability_identifiers, :project_id, :integer
    change_column :vulnerability_occurrence_pipelines, :pipeline_id, :integer
    change_column :vulnerability_occurrences, :project_id, :integer
    change_column :vulnerability_scanners, :project_id, :integer
    change_column :vulnerability_user_mentions, :note_id, :integer
    change_column :web_hook_logs, :web_hook_id, :integer
    change_column :web_hook_logs_archived, :id, :integer
    change_column :web_hook_logs_archived, :web_hook_id, :integer
    change_column :web_hooks, :id, :integer
    change_column :web_hooks, :project_id, :integer
    change_column :web_hooks, :service_id, :integer
    change_column :web_hooks, :group_id, :integer
    change_column :webauthn_registrations, :u2f_registration_id, :integer
    change_column :wiki_page_meta, :id, :integer
    change_column :wiki_page_slugs, :id, :integer

    execute <<-EOS
      CREATE TRIGGER trigger_has_external_issue_tracker_on_delete AFTER DELETE ON services FOR EACH ROW WHEN ((((old.category)::text = 'issue_tracker'::text) AND (old.active = true) AND (old.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_issue_tracker();
      CREATE TRIGGER trigger_has_external_issue_tracker_on_insert AFTER INSERT ON services FOR EACH ROW WHEN ((((new.category)::text = 'issue_tracker'::text) AND (new.active = true) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_issue_tracker();
      CREATE TRIGGER trigger_has_external_issue_tracker_on_update AFTER UPDATE ON services FOR EACH ROW WHEN ((((new.category)::text = 'issue_tracker'::text) AND (old.active <> new.active) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_issue_tracker();
      CREATE TRIGGER trigger_has_external_wiki_on_delete AFTER DELETE ON services FOR EACH ROW WHEN ((((old.type)::text = 'ExternalWikiService'::text) AND (old.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_wiki();
      CREATE TRIGGER trigger_has_external_wiki_on_insert AFTER INSERT ON services FOR EACH ROW WHEN (((new.active = true) AND ((new.type)::text = 'ExternalWikiService'::text) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_wiki();
      CREATE TRIGGER trigger_has_external_wiki_on_update AFTER UPDATE ON services FOR EACH ROW WHEN ((((new.type)::text = 'ExternalWikiService'::text) AND (old.active <> new.active) AND (new.project_id IS NOT NULL))) EXECUTE PROCEDURE set_has_external_wiki();
    EOS
  end
end
