#!/bin/sh
set -e
WORKHORSE_DIR=workhorse/
WORKHORSE_REF="v$(cat GITLAB_WORKHORSE_VERSION)"

if [ $# -gt 1 ] || ([ $# = 1 ] && [ x$1 != xcheck ]); then
  echo "Usage: update-workhorse [check]"
  exit 1
fi

clean="$(git status --porcelain)"
if [ -n "$clean" ] ; then
  echo 'error: working directory is not clean:'
  echo "$clean"
  exit 1
fi

git fetch https://gitlab.com/gitlab-org/gitlab-workhorse.git "$WORKHORSE_REF"
git rm -rf --quiet -- "$WORKHORSE_DIR"
git read-tree --prefix="$WORKHORSE_DIR" -u FETCH_HEAD

status="$(git status --porcelain)"

if [ x$1 = xcheck ]; then
  if [ -n "$status" ]; then
    echo "error: $WORKHORSE_DIR does not match $WORKHORSE_REF"
    exit 1
  fi
  exit 0
fi

if [ -z "$status" ]; then
  echo "warn: $WORKHORSE_DIR is already up to date, exiting without commit"
  exit 0
fi

tree=$(git write-tree)
msg="Update vendored workhorse to $WORKHORSE_REF"
commit=$(git commit-tree -p HEAD -p FETCH_HEAD^{commit} -m "$msg" "$tree")
git update-ref HEAD "$commit"
git log -1
